version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=0
      - DATABASE_URL=sqlite:///nlp_assignment_tracker.db
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  celery:
    build: .
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
    restart: always

volumes:
  db_data: 